UnoRefactored/WebApp/Pages/Play/Index.cshtml.cs
using DAL;
using Domain;
using Domain.Database;
//using Domain.Database;
using GameEngine;
using MenuSystem;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Player = Domain.Player;

namespace WebApp.Pages.Play;

[ValidateAntiForgeryToken]
public class Index : PageModel
{
    private readonly DAL.AppDbContext _context;
    private readonly IGameRepository _gameRepository = default!;
    private GameOptions gameOptions = new GameOptions();
    public UnoGameEngine Engine { get; set; } = default!;
    public GameState State { get; set; } = default!;
    Dictionary<Guid, Guid>playerIdMapping = new Dictionary<Guid, Guid>();
    public Player? ClickedPlayer { get; private set; }
    public bool HasDrawnCard { get; set; }
    
    public Index(AppDbContext context)
    {
        _context = context;
        _gameRepository = new GameRepositoryEF(_context);
    }

    [BindProperty(SupportsGet = true)] public Guid GameId { get; set; }
    [BindProperty(SupportsGet = true)] public Guid PlayerId { get; set; }
    [BindProperty(SupportsGet = true)] public Guid CardId { get; set; }

    [BindProperty(SupportsGet = true)] public PlayerTurn Turn { get; set; } = new PlayerTurn();
    [BindProperty(SupportsGet = true)] public Guid ClickedPlayerId { get; set; }
    [BindProperty(SupportsGet = true)] public string? GameMode { get; set; }

    
    public IActionResult OnGet()
    {
        var gameState = _gameRepository.LoadGame(GameId);

        if (gameState == null)
        {
            gameState = new GameState
            {
                Id = GameId,
                IsInitialised = false,
            };
        }
        
        var waitingPlayers = _context.Players
            .Where(p => p.GameId == GameId && p.NickName.StartsWith("Waiting for Player nr"))
            .ToList();

        if (waitingPlayers.Any())
        {
            ViewData["WaitingForPlayers"] = true;
        }
        
        if (!gameState.IsInitialised)
            {
                Engine = new UnoGameEngine(gameOptions)
                {
                    State = gameState
                };

                foreach (var contextPlayer in _context.Players)
                {
                    if (contextPlayer.GameId == GameId)
                    {
                        _context.Entry(contextPlayer).State = EntityState.Detached;
                        var domainPlayer = new Domain.Player
                        {
                            Id = contextPlayer.Id,
                            NickName = contextPlayer.NickName,
                            PlayerType = contextPlayer.PlayerType,
                        };
                        Console.WriteLine(domainPlayer.Id);
                        gameState.Players.Add(domainPlayer);
                        playerIdMapping[contextPlayer.Id] = domainPlayer.Id;
                    }
                }
                gameState.PlayerIdMapping = playerIdMapping;
                Engine.DeckBuilder();
                Engine.ShuffleAndDistributeCards();
                HttpContext.Session.SetString("NotInitialised", "true");
                gameState.IsInitialised = true;
                gameState.ActivePlayerNo = 0;
                
                
                //var PlayerId = Engine.GetActivePlayer().Id;
                
                _gameRepository.SaveGame(GameId, gameState);
                
                
                //return RedirectToPage("/Play/Index", new { gameId = GameId, playerId = PlayerId });

            }
            else
            {
                Engine = new UnoGameEngine(gameOptions)
                {
                    State = gameState
                };
                Engine.State.IsInitialised = true;
                //_gameRepository.SaveGame(GameId, gameState);
            }
        
        //if AI turn take AI action
        //If human turn take human action
        
        Player activePlayer;
        activePlayer = Engine.GetActivePlayer();
        while (IsAiPlayerActive())
        {
            PlayerTurn currentTurn = new PlayerTurn()
            {
                Result = ETurnResult.GameStart,
                Card = Engine.State.DiscardPile.DiscardedCards.Last(),
                DeclaredColor = Engine.State.DiscardPile.DiscardedCards.Last()!.CardColor
            };
            
            currentTurn = Engine.PlayTurn(currentTurn, Engine.State.DrawDeck);
            if (currentTurn.Card != null)
            {
                Engine.State.DiscardPile.DiscardedCards.Add(currentTurn.Card);
                Engine.State.Players[Engine.State.ActivePlayerNo].PlayerHand.Remove(currentTurn.Card);
            }
            
            _gameRepository.SaveGame(GameId, gameState);
            Engine.NextPlayerTurn();
        }
        
        ClickedPlayerId = gameState.Players.FirstOrDefault(p => p.Id == PlayerId)?.Id ?? Engine.GetActivePlayer().Id;
        ClickedPlayer = gameState.Players.FirstOrDefault(p => p.Id == ClickedPlayerId && p.PlayerType == EPlayerType.Human) ?? Engine.GetActivePlayer();
        
        //ClickedPlayer = gameState.Players.FirstOrDefault(p => p.Id == PlayerId) ?? Engine.GetActivePlayer(); 
        _gameRepository.SaveGame(GameId, gameState);
        return Page();
    }
    
    public IActionResult OnPostDrawCard()
    {
            var gameState = _gameRepository.LoadGame(GameId);
            Engine = new UnoGameEngine(gameOptions)
            {
                State = gameState
            };
            GameCard Card;

            if (!gameState.HasDrawnCard)
            {
                Card = Engine.DrawCard(gameState)!;
                Engine.GetActivePlayer().PlayerHand.Add(Card);
                gameState.HasDrawnCard = true;
                _gameRepository.SaveGame(GameId, gameState);
                return RedirectToPage("/Play/Index", new { gameId = GameId, playerId = Engine.GetActivePlayer().Id });
            }
            else
            {
                TempData["ErrorMessage"] = "You have already drawn a card this turn.";
                return RedirectToPage("/Play/Index", new { gameId = GameId, playerId = Engine.GetActivePlayer().Id });
            }
            
    }

    public IActionResult OnPostEndTurn()
    {
        var gameState = _gameRepository.LoadGame(GameId);
        Engine = new UnoGameEngine(gameOptions)
        {
            State = gameState
        };
        bool hasPlayableCard =
            Engine.GetCardsPlayerCanPlay(gameState.Players[gameState.ActivePlayerNo]).Count > 0;
        if (!hasPlayableCard)
        {
            gameState.HasDrawnCard = false;
            Engine.SkipPlayerMove();
            Engine.NextPlayerTurn();
            _gameRepository.SaveGame(GameId, gameState);
            return RedirectToPage("/Play/Index", new { gameId = GameId });
        }
        TempData["ErrorMessage"] = "You have playable cards!";
        return Page();
    }


    public IActionResult OnPostPlayCard()
    {
        try
        {
            var gameId = Guid.Parse(Request.Form["GameId"]);
            var cardIndex = int.Parse(Request.Form["CardIndex"]);
            
            Console.WriteLine(cardIndex);
            var gameState = _gameRepository.LoadGame(GameId);
            Engine = new UnoGameEngine(gameOptions)
            {
                State = gameState
            };
            
            var currentPlayer = Engine.GetActivePlayer();
            //var currentPlayer = gameState.Players.FirstOrDefault(p => p.Id == PlayerId);
            if (currentPlayer == null || currentPlayer != Engine.GetActivePlayer())
            {
                TempData["ErrorMessage"] = $"It is not your turn. Wait for your turn! Current player name is {currentPlayer?.NickName}";
                return RedirectToPage("/Play/Index", new { gameId = GameId, playerId = currentPlayer!.Id });
            }
            
            if (!Engine.ValidatePlayerMove(cardIndex + 1))
            {
                TempData["ErrorMessage"] = "Invalid move. Please select a valid card to play.";
                return RedirectToPage("/Play/Index", new { gameId = GameId, playerId = Engine.GetActivePlayer().Id });
            }
            
            Engine.MakePlayerMove(cardIndex + 1);
            gameState.HasDrawnCard = false;
            Engine.NextPlayerTurn();

            if (!IsAiPlayerActive())
            {
                ClickedPlayer = currentPlayer;
            }
            
            
            _gameRepository.SaveGame(gameId, gameState);
            TempData["SuccessMessage"] = "Card played, wait for your next turn.";
            return RedirectToPage("/Play/Index", new { gameId = GameId, playerId = Engine.GetActivePlayer().Id });
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Exception in OnPostPlayCard: {ex.Message}");
            return new JsonResult(new { success = false, message = $"Error playing the card. Exception details: {ex.Message}" });
        }
    }
    
    private bool IsAiPlayerActive()
    {
        var activePlayerNo = Engine.State.ActivePlayerNo;

        // Check if activePlayerNo is a valid index
        if (activePlayerNo >= 0 && activePlayerNo < Engine.State.Players.Count)
        {
            var activePlayer = Engine.State.Players[activePlayerNo];

            // Check if activePlayer is not null and has PlayerType property
            if (activePlayer != null && (activePlayer.PlayerType == EPlayerType.AI || activePlayer.PlayerType == EPlayerType.Human))
            {
                return activePlayer.PlayerType == EPlayerType.AI;
            }
        }
        // Return false if any check fails
        return false;
    }
    
}

UnoRefactored/WebApp/Pages/Play/Index.cshtml
@page
@using Domain
@using GameEngine
@using Microsoft.VisualStudio.TextTemplating
@using Mono.TextTemplating
@model WebApp.Pages.Play.Index

@{
    ViewData["Title"] = "Play";
}


@foreach (var player in Model.Engine.State.Players)
{
    <p>@player.NickName</p>
}

@if (ViewData["WaitingForPlayers"] != null && (bool)ViewData["WaitingForPlayers"])
{
    <div>
        <p>Waiting for all players to join the game.</p>
    </div>
}
else
{
    <div>
        <p>All Players have joined the game.</p>
    </div>
    @if (Model.HasDrawnCard)
    {
        
    }
    <h3>Play</h3>
    <h3 class="text-center">Current active player: @Model.Engine.GetActivePlayer().NickName</h3>
    <h3>@Model.Engine.State.ActivePlayerNo</h3>
                                          
    <h5>Reload page in <span id="reload-label">-</span></h5>
                                                       
    <h3>Cards in Deck:</h3>
    <h>@Model.Engine.State.DrawDeck.Count</h>

    <div class="top-discard-container">
        <div class="top-discard">
            <h3>Top Discard:</h3>
            <div class="card num-@Model.Engine.State.DiscardPile.GetLastCardInDiscardPile()?.CardValue @Model.Engine.State.DiscardPile.GetLastCardInDiscardPile()?.CardColor">
                <span class="inner">
                    <span class="mark">@ConvertCardValueToNumber(@Model.Engine.State.DiscardPile.GetLastCardInDiscardPile()!.CardValue)</span>
                </span>
            </div>
        </div>
    </div>


    <div class="current-players">
        <h3>Players currently playing</h3>
        <table>
            <tr>
                <th>Player Names:</th>
                <th>Cards in Hand:</th>
            </tr>
            @foreach (var player in Model.Engine.State.Players)
            {
                <tr>
                    <td>@player.NickName</td>
                    <td>@player.PlayerHand.Count</td>
                </tr>
            }
        </table>
    </div>
    
    <p>Active player Hand:</p>
    <div class="active-player-hand">
        Cards:
        @for (int i = 0; i < Model.ClickedPlayer!.PlayerHand.Count; i++)
        {
            var card = Model.ClickedPlayer.PlayerHand[i];
            <form id="playCardForm_@i" method="post" asp-page-handler="PlayCard">
                <input type="hidden" name="GameId" value="@Model.GameId" />
                <input type="hidden" name="PlayerId" value="@Model.PlayerId" />
                <input type="hidden" name="CardIndex" value="@i" />
                <a href="javascript:void(0);" class="card-container" onclick="playCard(@i)">
                    <div class="card num-@card.CardValue @card.CardColor">
                        <span class="inner">
                            <span class="mark">@ConvertCardValueToNumber(card.CardValue)</span>
                        </span>
                    </div>
                </a>
            </form>
        }
    </div>
    
    <p>Player actions: </p>
    <form method="post" asp-page-handler="DrawCard">
         @Html.AntiForgeryToken()
         <input type="hidden" name="GameId" value="@Model.GameId" />
         <input type="hidden" name="PlayerId" value="@Model.PlayerId" />
         <button id="drawCardButton" type="submit">Draw Card</button>
    </form>
        <form method="post" asp-page-handler="EndTurn">
            @Html.AntiForgeryToken()
            <input type="hidden" name="GameId" value="@Model.GameId" />
            <input type="hidden" name="PlayerId" value="@Model.PlayerId" />
            <button id="endTurnButton" type="submit">End Turn</button>
    </form>

}

<p>Clicked Player: @Model.ClickedPlayer?.NickName</p>

<!-- Display the clicked player's hand -->
<ul>
    @foreach (var card in Model.ClickedPlayer!.PlayerHand)
    {
        <li>@card.CardColor, @card.CardValue</li>
    }
</ul>


<p id="drawnCardMessage"></p>

@{
    // Check if there is a TempData message from the server
    var errorMessage = TempData["ErrorMessage"] as string;
    var successMessage = TempData["SuccessMessage"] as string;
}

<p id="playCardMessage">@errorMessage</p>
<p id="playCardMessage2">@successMessage</p>


@* <h3>Active player: @Model.Engine.State.Players - @Model.Engine.GetActivePlayer().NickName</h3>  *@
@*
<h3>Active player: @Model.Engine.GetActivePlayer().NickName</h3> 
*@


@if (Model.Engine.GetActivePlayer().Id == Model.PlayerId)
{
    <div>Yes, Active</div>
}

@section Scripts
{
    <script>
        let timerValue = 100
        let timerLabel = document.querySelector("#reload-label")
        setInterval(() => {
            timerValue--
            timerLabel.innerHTML = timerValue.toString()
            if (timerValue <= 0) {
                window.location.reload()
                }
        }, 1000)
    </script>
    
    <script>
    function playCard(index) {
        document.getElementById('playCardForm_' + index).submit();    
    }
    </script>
}


@functions {

    string ConvertCardValueToNumber(EValue cardValue)
    {
        switch (cardValue)
        {
            case EValue.One:
                return "1";
            case EValue.Two:
                return "2";
            case EValue.Three:
                return "3";
            case EValue.Four:
                return "4";
            case EValue.Five:
                return "5";
            case EValue.Six:
                return "6";
            case EValue.Seven:
                return "7";
            case EValue.Eight:
                return "8";
            case EValue.Nine:
                return "9";
            case EValue.Skip:
                return "S";
            case EValue.Reverse:
                return "R";
            case EValue.DrawTwo:
                return "D2";
            case EValue.DrawFour:
                return "D4";
            case EValue.Wild:
                return "W";
            default:
                return "-"; // If no conversion is needed
        }
    }

    private bool IsAiPlayerActive()
    {
        var activePlayerNo = Model.Engine.State.ActivePlayerNo;

        // Check if activePlayerNo is a valid index
        if (activePlayerNo >= 0 && activePlayerNo < Model.Engine.State.Players.Count)
        {
            var activePlayer = Model.Engine.State.Players[activePlayerNo];

            // Check if activePlayer is not null and has PlayerType property
            if (activePlayer != null && (activePlayer.PlayerType == EPlayerType.AI || activePlayer.PlayerType == EPlayerType.Human))
            {
                return activePlayer.PlayerType == EPlayerType.AI;
            }
        }
        // Return false if any check fails
        return false;
    }

}